### ISSUE TITLE
Missed `elements` arg for `elementResizeDetector.uninstall()`

### ISSUE THREAD

**Issue by newsiberian** [doitadrian/react-columned#1]
I received an error:
![Screenshot_20190924_232857](https://user-images.githubusercontent.com/11130487/65530957-1d4dd400-df23-11e9-8591-b5511c3c9874.png)
which goes from here:
```js
return function () {
      if (elementResizeDetector) {
        elementResizeDetector.uninstall();
        elementResizeDetector = null;
      }
    };
```
`Uninstall` method has a required argument `elements`. I believe it should be a ref in our case.
![Screenshot_20190924_233138](https://user-images.githubusercontent.com/11130487/65531175-7b7ab700-df23-11e9-891a-0e7660a8a1b1.png)

## This is:

- Bug

**Comment by adrians5j** [comment]
Fixed by #2 

Thanks @newsiberian for reporting and @NexisSis for submitting his PR.
